_BASE_: "Base-C2_L_R5021k_640b64_4x.yaml"
MODEL:
  MASK_ON: False

  ROI_HEADS:
    NUM_CLASSES: 13204

DATASETS:
  TRAIN: ("v3det_train",)
  TEST: ("v3det_val",)

SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 10000
