_BASE_: "Base-C2_L_R5021k_640b64_4x.yaml"
MODEL:
  MASK_ON: False
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    IMAGE_LABEL_LOSS: 'max_size'
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/v3det_2023_v1_train_clip_a+cname.npy'
    CAT_FREQ_PATH: 'datasets/metadata/v3det_2023_v1_ovd_base_cat_info.json'
    USE_FED_LOSS: False

  ROI_HEADS:
    NAME: V3DetDeticCascadeROIHeads
    NUM_CLASSES: 13204
  WEIGHTS: v3det_ovd_base.pth

SOLVER:
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
DATASETS:
  TRAIN: ("v3det_ovd_train","imagenet_v3det_cls_100")
  TEST: ("v3det_val",)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  # DATASET_RATIO: [1, 4]
  # DATASET_BS: [8, 32]
  DATASET_RATIO: [1, 12]
  DATASET_BS: [8, 96]
  USE_DIFF_BS_SIZE: True
  DATASET_INPUT_SIZE: [640, 320]
  USE_RFS: [True, False]
  DATASET_INPUT_SCALE: [[0.1, 2.0], [0.5, 1.5]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True