DATA:
    ROOT: 'data/'
    TRAIN_FILE: 'data/k722_train.txt'
    VAL_FILE: 'data/k722_val.txt'
    DATASET: kinetics722
    NUM_FRAMES: 8
    TUBELET_SIZE: 1
    NUM_CLASSES: 722
    LABEL_LIST: 'labels/kinetics722_labels.csv'
MODEL:
    ARCH: eva-1b/14
    DROP_PATH_RATE: 0.3
    PRETRAINED: /path/to/eva_psz14.pt  # download from https://huggingface.co/BAAI/EVA/blob/main/eva_psz14.pt
    PRETRAINED_MODE: 'eva'
TRAIN:
    BATCH_SIZE: 2
    ACCUMULATION_STEPS: 1
    BETAS: (0.9, 0.98)
    EPS: 1e-6
    LR: 8.e-6
    LAYER_WISE_DECAY: 1.0
    WEIGHT_DECAY: 0.05
    EPOCHS: 40
    WARMUP_EPOCHS: 5
    USE_CHECKPOINT: True
MYCLIP:
    USE_LEARNABLE_POS_EMB: True
    STOP_GRAD_CONV1: False
    USE_MEAN_POOLING: True
    USE_TEXT_EMBED: False
